export default [
    {
        label:'Name',
        type:'text',
        name:'name',
        model:'name',
    },
    {
        label:'description',
        type:'text',
        name:'description',
        model:'description',
    },
    {
        label:'manufacturer',
        type:'text',
        name:'manufacturer',
        model:'manufacturer',
    },
    {
        label:'unitOfMeasurement',
        type:'text',
        name:'unitOfMeasurement',
        model:'unitOfMeasurement',
    },
    {
        label:'catalogNumber',
        type:'text',
        name:'catalogNumber',
        model:'catalogNumber',
    },
    {
        label:'quantityInStock',
        type:'text',
        name:'quantityInStock',
        model:'quantityInStock',
    },
    {
        label:'purchaseDate',
        type:'date',
        name:'purchaseDate',
        model:'purchaseDate',
    },
    {
        label:'deliveryDate',
        type:'date',
        name:'deliveryDate',
        model:'deliveryDate',
    },
    {
        label:'expiryDate',
        type:'date',
        name:'expiryDate',
        model:'expiryDate',
    },
    {
        label:'category',
        type:'text',
        name:'category',
        model:'category',
    },
    {
        label:'minimumStockLevel',
        type:'text',
        name:'minimumStockLevel',
        model:'minimumStockLevel',
    },
]
