export default {
    LogIn: "Log In",
    EnterYourEmail: "Enter your email:",
    Login: "Login",
    EnterYourPassword: "Enter your password:",
    RememberMe: "Remember me",
    Password: "Password",
    Confirm: "Confirm",
    Registration: "Registration",
    SignUp: "Sign up",
    ProvideYourName: "Provide your name:",
    Name: "Name",
    Surname: "Surname",
    Email: "Email",
    RepeatThePassword: "Repeat the password:",
    ProvideYourSurname: "Provide your surname:",
    Warehouse: "Warehouse",
    Description: "Description",
    Manufacturer: "Manufacturer",
    UnitOfMeasurement: "Unit of measurement",
    CatalogNumber: "Catalog number",
    QuantityInStock: "Quantity in stock",
    PurchaseDate: "Purchase date",
    DeliveryDate: "Delivery date",
    ExpiryDate: "Expiry date",
    Category: "Category",
    MinimumStockLevel: "Min. stock level",
    Notifications: "Notifications",
    Id: "Id",
    Title: "Title",
    TypeNotification: "Notification type",
    CreateAccountForEmployee: "Create an account for an employee",
    TypeUser: "Type user:",
    ConstructionManager: "Construction manager",
    WarehouseManager: "Warehouse manager",
    Secretariat: "Secretariat",
    SuccessfullyRegisteredUserEmailWithVerificationLinkHasBeenSent: "Successfully registered user, an email with a verification link has been sent",
    UserHasBeenSuccessfullyVerified: "User has been successfully verified",
    RedirectingToTheLoginPage: "Redirecting to the login page",
    InvalidEmailAddressFormat: "Invalid email address format",
    ThePasswordShouldContain6Characters1UppercaseLetterAnd1SpecialCharacter: "The password should contain 6 characters, 1 uppercase letter, and 1 special character",
    TheEnteredPasswordsDoNotMatch: "The entered passwords do not match",
    CreateNewProduct: "Create New Product",
    UpdateProduct: "update product with id"
}