export default {
    LogIn: "Zaloguj się",
    EnterYourEmail: "Podaj swój e-mail:",
    Login: "Login",
    EnterYourPassword: "Podaj hasło:",
    RememberMe: "Zapamiętaj mnie",
    Password: "Hasło",
    Confirm: "Zatwierdź",
    Registration: "Rejestracja",
    SignUp: "Zarejestruj się",
    ProvideYourName: "Podaj imię:",
    Name: "Imię",
    Name2: "Nazwa",
    Surname: "Nazwisko",
    Email: "Email",
    RepeatThePassword: "Powtórz hasło:",
    ProvideYourSurname: "Podaj nazwisko:",
    Warehouse: "Magazyn",
    Description: "Opis",
    Manufacturer: "Producent",
    UnitOfMeasurement: "Jednostka miary",
    CatalogNumber: "Numer katalogowy",
    QuantityInStock: "Ilość na magazynie",
    PurchaseDate: "Data zakupu",
    DeliveryDate: "Data dostawy",
    ExpiryDate: "Data ważności",
    Category: "Kategoria",
    MinimumStockLevel: "Min. poziom zapasów",
    Notifications: "Powiadomienia",
    Id: "Id",
    Title: "Tytuł",
    TypeNotification: "Typ powiadomienia",
    CreateAccountForEmployee: "Stwórz konto dla pracownika",
    TypeUser: "Typ użytkownika:",
    ConstructionManager: "Kierownik budowy",
    WarehouseManager: "Kierownik magazynu",
    Secretariat: "Sekretariat",
    SuccessfullyRegisteredUserEmailWithVerificationLinkHasBeenSent: "Pomyślnie zarejestrowano użytkownika, wysłano maila z linkiem weryfikacyjnym",
    UserHasBeenSuccessfullyVerified: "Użytkownik został pomyślnie zweryfikowany",
    RedirectingToTheLoginPage: "Przenoszenie do strony logowania",
    InvalidEmailAddressFormat: "Niepoprawny format adresu email",
    ThePasswordShouldContain6Characters1UppercaseLetterAnd1SpecialCharacter: "Hasło powinno zawierać 6 znaków, 1 dużą literę oraz 1 znak specjalny",
    TheEnteredPasswordsDoNotMatch: "Hasła nie są takie same",
    CreateNewProduct: "Stwórz nowy produkt",
    UpdateProduct: "Zaktualizuj produkt o id",
    TemporaryWarehouse: "Magazyny tymczasowe",
    ConstructionManagerFirstName: "Imię kierownika budowy",
    ConstructionManagerLastName: "Nazwisko kierownika budowy",
    TemporaryWarehouseName: "Nazwa magazynu tymczasowego",
    TemporaryWarehouse_id: "Magazyn tymczasowy",
    AddProductToTemporaryWarehouseById: "Dodaj produkt do magazynu tymczasowego",
    temporaryWarehouseId : "Id magazynu tymczasowego",
    warehouseId : "Id produktu",
    quantity: "ilość",
    TemporaryErrorWarehouse:"Wybierz Id produktu!",
    TemporaryErrorQuantity:"Ilość nie może być zerem lub na minusie!!",
    WarehouseNameError:"Nazwa magazynu jest za krótka co najmniej 4 znaki!",
    Details: "Szczegóły",
    ReportDetails:"Szczegóły zgłoszenia",
    back:"WSTECZ",
    add:"DODAJ",
    AddProduktToReport:"Dodaj Przedmiot",
    InternalReports:"Zgłoszenia wewnętrzne",
    EndMaterial:"Kończące się materiały",
    LogOut: "Wyloguj"

}
