export default {
    LogIn: "Увійти",
    EnterYourEmail: "Введіть свій електронний адрес:",
    Login: "Логін",
    EnterYourPassword: "Введіть пароль:",
    RememberMe: "Запам'ятати мене",
    Password: "Пароль",
    Confirm: "Підтвердити",
    Registration: "Реєстрація",
    SignUp: "Зареєструватися",
    ProvideYourName: "Введіть своє ім'я:",
    Name: "Ім'я",
    Name2: "Назва",
    Surname: "Прізвище",
    Email: "Електронна пошта",
    RepeatThePassword: "Повторіть пароль:",
    ProvideYourSurname: "Введіть своє прізвище:",
    Warehouse: "Сховище",
    Description: "Опис",
    Manufacturer: "Виробник",
    UnitOfMeasurement: "Одиниця виміру",
    CatalogNumber: "Каталожний номер",
    QuantityInStock: "Кількість на складі",
    PurchaseDate: "Дата покупки",
    DeliveryDate: "Дата доставки",
    ExpiryDate: "Термін придатності",
    Category: "Категорія",
    MinimumStockLevel: "Мінімальний рівень запасів",
    Notifications: "Сповіщення",
    Id: "Ідентифікатор",
    Title: "Назва",
    TypeNotification: "Тип сповіщення",
    CreateAccountForEmployee: "Створити обліковий запис для співробітника",
    TypeUser: "Тип користувача:",
    ConstructionManager: "Керівник будівництва",
    WarehouseManager: "Керівник складу",
    Secretariat: "Секретаріат",
    SuccessfullyRegisteredUserEmailWithVerificationLinkHasBeenSent: "Користувача успішно зареєстровано, відправлено лист з посиланням для підтвердження",
    UserHasBeenSuccessfullyVerified: "Користувача успішно підтверджено",
    RedirectingToTheLoginPage: "Перенаправлення на сторінку входу",
    InvalidEmailAddressFormat: "Неправильний формат електронної пошти",
    ThePasswordShouldContain6Characters1UppercaseLetterAnd1SpecialCharacter: "Пароль повинен містити 6 символів, 1 велику літеру та 1 спеціальний символ",
    TheEnteredPasswordsDoNotMatch: "Введені паролі не співпадають",
    CreateNewProduct: "Створити новий продукт",
    UpdateProduct: "Оновити продукт з ідентифікатором",
    TemporaryWarehouse: "Тимчасові склади",
    ConstructionManagerFirstName: "Ім'я керівника будівництва",
    ConstructionManagerLastName: "Прізвище керівника будівництва",
    TemporaryWarehouseName: "Назва тимчасового складу",
    TemporaryWarehouse_id: "Тимчасовий склад",
    AddProductToTemporaryWarehouseById: "Додати продукт до тимчасового складу за ідентифікатором",
    temporaryWarehouseId: "Ідентифікатор тимчасового складу",
    warehouseId: "Ідентифікатор продукту",
    quantity: "Кількість",
    TemporaryErrorWarehouse: "Виберіть ідентифікатор продукту!",
    TemporaryErrorQuantity: "Кількість не може бути нулем або від'ємною!",
    WarehouseNameError: "Назва складу занадто коротка, мінімум 4 символи!",
    Details: "Деталі",
    ReportDetails: "Деталі звіту",
    back: "НАЗАД",
    add: "ДОДАТИ",
    AddProduktToReport: "Додати продукт до звіту",
    InternalReports: "Внутрішні звіти",
    EndMaterial: "Закінчуючіся матеріали",
    LogOut: "Вийти"
}
